export {default as Home } from './Home'
export {default as About } from './About'
export {default as Error404 } from './Error404'
export {default as CharacterDetail } from './CharacterDetail'
export {default as Register } from './Register'